version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: proxysafe
      PGDATA: /data/postgres
    ports:
      - "5435:5432"
    volumes:
      - ./dev/pg/:/var/lib/pg