# local
db:
  base:
    pg_read_nodes:
      - postgres://postgres:example@localhost:5435/proxysafe?sslmode=disable # local
    pg_write_nodes:
      - postgres://postgres:example@localhost:5435/proxysafe?sslmode=disable # local

signing_key: abc

token_ttl: 10