name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Install packages
        run: go get ./...
      
      - name: Build
        run: go build -o proxysafe
      
      - name: Install sshpass
        run: sudo apt install sshpass

      - name: Deploy binary
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
        run: sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./proxysafe root@92.63.97.207:/home/rkuzin/proxysafe/releases/current/

      - name: Deploy config
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
        run: sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./config/* root@92.63.97.207:/home/rkuzin/proxysafe/releases/current/config/

      - name: Deploy scripts
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
        run: sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./deploy/* root@92.63.97.207:/home/rkuzin/proxysafe/releases/current/deploy/
      
      - name: Deploy migrations
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
        run: sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./migrations/* root@92.63.97.207:/home/rkuzin/proxysafe/releases/current/migrations/

      