name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Install packages
        run: go get ./...
      
      - name: Build
        run: go build -o proxysafe
      
      - name: Install sshpass
        run: sudo apt install sshpass

      - name: Deploy
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
        run: sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* root@92.63.97.207:/home/rkuzin/proxysafe/releases/current/

      - name: Run migrations
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
        run: sshpass -p $PASSWORD ssh root@92.63.97.207 '/home/rkuzin/proxysafe/releases/db/migrate.sh'

      - name: Restart
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
        run: sshpass -p $PASSWORD ssh root@92.63.97.207 'systemctl restart proxysafe'
      