name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Install packages
        run: go get ./...
      
      - name: Build
        run: go build -o proxysafe

      - name: Test
        run: go test ./...
      
      - name: Install sshpass
        run: sudo apt install sshpass

      - name: Deploy
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
        run: |
          sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* root@92.63.97.207:/home/rkuzin/proxysafe/releases/current/
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@92.63.97.207 '/home/rkuzin/proxysafe/releases/db/migrate.sh'
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@92.63.97.207 'systemctl restart proxysafe'
      
      - name: Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} successfully pushed commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      